### ISSUE TITLE
Sourcemaps not found

### ISSUE THREAD

**Issue by lorenzodianni** [getsentry/sentry-cordova#366]
I have an application built with Angular and Cordova.
Initially, I implemented Sentry using the `@sentry/angular` package and created releases on Sentry via the CLI using `getsentry/action-release`. With this setup, I never had any issues with sourcemaps, errors were tracked correctly, and I could view everything without any problems directly on sentry.io.

Then, I removed `@sentry/angular` and implemented `sentry-cordova` because I needed to capture app crashes.

Since making this change, errors in Sentry no longer find the corresponding sourcemap, even though the file is present in the release and visible under [Settings] > Projects > PROJECT_NAME > Source Maps.

### Environment
```
node v20.11.0
@sentry/cli 2.39.0
sentry-cordova 1.4.1
```

### Expected Result

To view the errors correctly, using the uploaded sourcemap

### Setup JS

```
const Sentry = cordova.require('sentry-cordova.Sentry');
Sentry.init({
    dsn: this.env.sentry.dsn,
    environment: 'production',
    release: `graze@${version}`,
    integrations: [Sentry.browserTracingIntegration()],
    tracesSampleRate: 0.25,
  });
}
```

#### Sentry Github Step
```
    - name: Sentry Release
      uses: getsentry/action-release@v1.7.0
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry_auth_token }}
        SENTRY_ORG: ${{ inputs.sentry_org }}
        SENTRY_PROJECT: ${{ inputs.sentry_project }}
      with:
        environment: production
        version: 'graze@${{steps.build.outputs.app_version}}'
        sourcemaps: 'root/dist'
```

#### Missing sourcemap warning
<img width="567" alt="Image" src="https://github.com/user-attachments/assets/2879655d-b522-49c3-84c4-1dc1da94ad75" />

#### Sentry sourcemap uploads
<img width="567" alt="Image" src="https://github.com/user-attachments/assets/85b23f40-ca53-432b-b7e0-d0f2e5d44e56" />
